data-sources:
  dataSources:
    - name: data-base-1
      strategy: postgres
      url: jdbc:postgresql://localhost:5432/db1?useSSL=false
      table: users
      user: testuser
      password: testpass
      mapping:
        id: user_id
        username: login
        name: first_name
        surname: last_name

    - name: data-base-2
      strategy: postgres
      url: jdbc:postgresql://localhost:5433/db2?useSSL=false
      table: user_table
      user: testuser
      password: testpass
      mapping:
        id: ldap_login
        username: ldap_login
        name: name
        surname: surname